FROM python:3.8

WORKDIR /srv/app/

# base for python
COPY ./src/program_generator/requirements.txt /srv/app/src/program_generator/requirements.txt
RUN pip install -r src/program_generator/requirements.txt

# base for golang
RUN wget --no-verbose --show-progress --progress=bar:force:noscroll \
  https://golang.org/dl/go1.17.1.linux-amd64.tar.gz

RUN tar -C /usr/local -xzf ./go1.17.1.linux-amd64.tar.gz
RUN rm go1.17.1.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/srv/app/.go
ENV GOBIN=/srv/app/.go/bin
ENV GOGC=off

# fixed golang dependencies
RUN go get github.com/ethereum/go-ethereum

# get our version of geth
COPY ./go.mod /srv/app/
COPY ./go.sum /srv/app/
WORKDIR /srv/app/

# get the remainder of measurement code
COPY ./src/instrumentation_measurement /srv/app/src/instrumentation_measurement
RUN go build -o src/instrumentation_measurement/bin/geth_main github.com/imapp-pl/gas-cost-estimator/src/instrumentation_measurement/geth
