FROM alpine:3.14.2

RUN apk update && apk add g++ cmake git make

WORKDIR /srv/app/

RUN git clone --recursive -b wallclock https://github.com/imapp-pl/evmone.git

RUN mkdir -p /srv/app/evmone/build
WORKDIR /srv/app/evmone/build

RUN cmake .. -DEVMONE_TESTING=ON \
  && cmake --build . -- -j

WORKDIR /srv/app/evmone
