---
title: "Comparison of garbage collection configurations; for Gas Cost Estimator"
output: html_document
---

**TODO** very rough dump, needs cleaning up

```{r}
source('common.R')
```

## Data preparations

`programs.csv` as generated by `pg_marginal.py` with `--fullCSV` flag on.
```{r}
setwd("~/sources/imapp/gas-cost-estimator/src")
program_set_codename = "pg_marginal_full5_c50_step1_shuffle"
programs = read.csv(paste("../../local/", program_set_codename, ".csv", sep=""))
```

`result_*.csv` as generated by `src/measurements.py`. 
Invocation similar to: `make measure EVM=geth VOLUME_DIR=/home/user/sources/imapp/local PROGRAMS=pg_marginal_full5_c50_step1_shuffle SAMPLESIZE=50 NSAMPLES=4`. 

```{r fig.width=20}
setwd("~/sources/imapp/gas-cost-estimator/src")
suffix = ""
measurement_codename = paste0("1000_10", suffix)

result_geth_gc100 = load_data_set("geth_gc100", program_set_codename, measurement_codename)
result_geth_gcprogr = load_data_set("geth_gcprogr", program_set_codename, measurement_codename)
result_geth_gcoff = load_data_set("geth_gcoff", program_set_codename, measurement_codename)
all_envs = c("geth_gc100", "geth_gcprogr", "geth_gcoff")
results = rbind(result_geth_gc100, result_geth_gcprogr, result_geth_gcoff)
```

```{r}

measurements = sqldf("SELECT opcode, op_count, sample_id, run_id, measure_total_time_ns, env, results.program_id
                     FROM results
                     INNER JOIN
                       programs ON(results.program_id = programs.program_id)
                     WHERE op_count = 50")
measurements0 = sqldf("SELECT opcode, op_count, sample_id, run_id, measure_total_time_ns, env, results.program_id
                     FROM results
                     INNER JOIN
                       programs ON(results.program_id = programs.program_id)
                     WHERE op_count = 0")
measurements$opcode = factor(measurements$opcode, levels=unique(programs$opcode))
measurements0$opcode = factor(measurements0$opcode, levels=unique(programs$opcode))
head(measurements)
```

```{r}
measurements_mean = aggregate(measure_total_time_ns ~ env * opcode, measurements, median)
measurements_mean0 = aggregate(measure_total_time_ns ~ env * opcode, measurements0, median)
```

```{r fig.width=40}
boxplot(measure_total_time_ns ~ env * opcode, data=measurements[which(measurements$env!="geth_gcprogr"),], las=2, log="y")
boxplot(measure_total_time_ns ~ env * opcode, data=measurements0[which(measurements0$env!="geth_gcprogr"),], las=2, log="y")
```

```{r fig.width=25, fig.height=5}
gcprogr_relative_penalty = measurements_mean$measure_total_time_ns[which(measurements_mean$env=="geth_gcoff")] / measurements_mean$measure_total_time_ns[which(measurements_mean$env=="geth_gc100")]
plot(measurements_mean$opcode[which(measurements_mean$env=="geth_gcoff")], gcprogr_relative_penalty, las=2)
```

```{r fig.width=25, fig.height=5}
gcprogr_relative_penalty = measurements_mean0$measure_total_time_ns[which(measurements_mean0$env=="geth_gcoff")] / measurements_mean0$measure_total_time_ns[which(measurements_mean0$env=="geth_gc100")]
plot(measurements_mean$opcode[which(measurements_mean0$env=="geth_gcoff")], gcprogr_relative_penalty, las=2)
```