---
title: "R Notebook: initial exploration for Gas Cost Estimator"
output: html_notebook
---

```{r include=FALSE, fig.width=20}
library(sqldf)
```

## Data preparations

Read in the `programs.csv` as generated by `src/program_generator.py` with `--fullCSV` flag on:
```{r fig.width=20}
setwd("~/sources/imapp/gas-cost-estimator/src")
programs_evm = read.csv("../../local/programs.csv")
```

**NOTE** see exploration.Rmd for comments

```{r fig.width=20}
programs_evm = programs_evm[which(programs_evm$opcode_measured != "JUMP"), ]
programs_evm = programs_evm[which(programs_evm$opcode_measured != "JUMPI"), ]
programs_evm = programs_evm[which(programs_evm$opcode_measured != "RETURNDATACOPY"), ]
programs_evm = droplevels(programs_evm)

programs = rbind(programs_evm)
head(programs)
```

```{r fig.width=20}
programs$measured_op_position_evmone = programs$measured_op_position + 1
head(programs)
```

```{r fig.width=20}
setwd("~/sources/imapp/gas-cost-estimator/src")
result_geth = read.csv("../../local/result_geth_timer.csv")
result_geth$env = "geth"
results = rbind(result_geth)
head(results)
```

Combine the two tables to see only times of the measured opcodes.

```{r fig.width=20}
measurements = sqldf("SELECT opcode_measured, sample_id, run_id, measure_all_time_ns, measure_all_timer_time_ns, env
                     FROM results
                     INNER JOIN
                       programs ON(results.program_id = programs.program_id)
                     WHERE
                       (results.instruction_id = programs.measured_op_position AND results.env = 'geth')
                     ")

head(measurements)
```

```{r fig.width=20}

measurements_geth = measurements[which(measurements$env=="geth"), ]

measurements_geth$measure_all_time_ns_raw = measurements_geth$measure_all_time_ns
measurements = rbind(measurements_geth)

check_columns = c("env", "measure_all_time_ns", "measure_all_time_ns_raw")
N = nrow(measurements)
# N = 10000
head(measurements)
```

```{r fig.width=20}
N = 20000
plot(NULL, xlim=c(1, N), ylim=c(0, 30))
geth_color = rgb(0.1,0.1,0.7,0.5)
geth_time_color = rgb(0.1,0.1,0.7,1)

ma <- function(x, n = 100){stats::filter(x, rep(1 / n, n), sides = 2)}
measurements$measure_all_timer_time_ns_ma = ma(measurements$measure_all_timer_time_ns)
# lines(ma(measurements$measure_all_time_ns_raw), type = "l", col = geth_color)
lines(ma(measurements$measure_all_timer_time_ns), type = "l", col = geth_time_color)
```
